# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  percy: percy/agent@0.1.3

jobs:
  build:
    docker:
      - image: circleci/node:8.15.1-browsers
    working_directory: ~/gym-ui

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run prettier
      - run: npm run lint
      - run: npm run clean
      - run: npm run compile
      - run: npm run build-storybook

      - store_artifacts:
          path: ~/gym-ui/artifacts

  percy-tests:
    docker:
      - image: circleci/node:8.15.1-browsers
    working_directory: ~/gym-ui

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run snapshot
      - store_artifacts:
          path: ~/gym-ui/artifacts

workflows:
  build_and_test:
    jobs:
      - build
      # - percy-tests:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         # ignore PRs from dependabot so we don't boil off percy time needlessly
      #         ignore: /^dependabot/
      # - percy/finalize_all:
      #     requires:
      #       - build
      #       - percy-tests
